### ISSUE TITLE
Slow UI

### ISSUE THREAD

**Issue by Kagey-cmd** [basnijholt/lovelace-ios-themes#76] opened 2024-09-04 14:13 UTC
I submitted a ticket to Nabu Casa because my UI was slow to load. I thought it was due to some kind of networking issue. They asked if I was using iOS themes. I uninstalled iOS themes as a test and now everything loads very fast again. I don't know if this is an issue with iOS themes or themes in general.

**Comment by basnijholt** [comment] 2024-09-06 05:19
@rohankapoorcom  any idea if this can be caused by the base64 images?

**Comment by basnijholt** [comment] 2024-09-06 05:21
@Kagey-cmd, can you share the link to the discussion with Nabu Casa?

Thanks for reporting!

**Comment by rohankapoorcom** [comment] 2024-09-06 05:34
@basnijholt - it's possible. Base64 encoding the background and shipping them with the html means it cannot be cached (as it could when it's an image file). So it will be downloaded every time the page is opened.

Alternative would be to host the images on a CDN and grab them that way (even github would be an option).

**Comment by Kagey-cmd** [comment] 2024-09-06 19:41
> @Kagey-cmd, can you share the link to the discussion with Nabu Casa?
> 
> Thanks for reporting!

**Me:** I've noticed recently that it takes several seconds longer to load my HA instance than I'm used to.
**Nabu Casa Support:** Can you restart HA in safe mode from the advanced options in the HA restart menu?
Do it continue to be slow in safe mode when all custom integrations and themes are disabled?
Specifically, do you use the iOS dark and light theme?
**Me:** I can try booting in safe mode later and I'll let you know.
Yes, I use the iOS dark and light themes. Are these causing issues?
**NC:** I have personally seen more than a few users with the issue and that specific theme in our Discord server. If you find that removing it resolves the issue, it may be good to report and share what you can with the developer of the theme.
https://github.com/basnijholt/lovelace-ios-themes

**Comment by basnijholt** [comment] 2024-09-07 02:20
@rohankapoorcom, I think we should try that. Especially since apparently it's causing problems for multiple people 😅

**Comment by basnijholt** [comment] 2024-09-07 07:08
@Kagey-cmd and @rohankapoorcom, this should now be fixed in version 3.0.0!

I switched to having a local version and remote version of the backgrounds.

Thanks again for bringing this to my attention @Kagey-cmd!

Please let me know whether this solves the problem.

**Closed** 2024-09-07 07:17 UTC

**Comment by Kagey-cmd** [comment] 2024-09-07 12:46
Thanks @basnijholt !
I'll test ASAP
